//
//  BlueViewController.swift
//  ObjectLibrary
//
//  Created by Umut on 17.02.2018.
//  Copyright © 2018 Umut. All rights reserved.
//

import UIKit

class BlueViewController: BasePageViewController {
 
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let button = UIButton(frame: CGRect(x: 40, y: 150, width: 100, height: 60))
        button.backgroundColor = UIColor.blue
        mainScrollView.addSubview(button)
        
        let label = UILabel(frame: CGRect(x: 0, y: 200, width: 200, height: 600))
        label.numberOfLines = 0
        label.text = "SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBWSDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW"
        mainScrollView.addSubview(label)
        
        let label2 = UILabel(frame: CGRect(x: 0, y: 200, width: 200, height: 600))
        label2.numberOfLines = 0
        label2.text = "SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBWSDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW SDFSDFS KFNWRLBW BVWVLWRJB VWROBW"
        
        mainScrollView.addSubview(label2)

        mainScrollView.contentSize = CGSize(width: mainScrollView.frame.size.width, height: button.frame.size.height + label.frame.size.height + label2.frame.size.height)
        
    }
}
