
line_length:
- 700 # warning
- 800 # error


excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
- Source/ExcludedFolder
- Source/ExcludedFile.swift

disabled_rules:
- trailing_whitespace
- identifier_name
- redundant_string_enum_value


