# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BookmarkMobile' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BookmarkMobile
  pod 'Alamofire', '~> 4.5'
  pod 'SwiftyJSON'
  pod 'ObjectMapper', '~> 3.0.0'
  pod 'SVProgressHUD'
  pod 'SnapKit', '~> 4.0'
  pod 'SwiftLint'

  
  target 'BookmarkMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BookmarkMobileUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
